# Generated by Django 5.0.2 on 2024-02-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_encryptedsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='value',
            field=models.TextField(),
        ),
    ]
