# Generated by Django 5.0.2 on 2024-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0005_alter_salary_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSalariesByArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('total', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EncryptedSalary',
        ),
    ]
