# Generated by Django 5.0.2 on 2024-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0006_totalsalariesbyarea_delete_encryptedsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='ci',
            field=models.BigIntegerField(default=0),
        ),
    ]
